public with sharing class PriceBookController {

    public class PriceBookWrapper {

    }

    public class PriceBookEntryWrapper {
        
    }
    
    @AuraEnabled
    public static String initPriceBooks() {

    }

    @AuraEnabled
    public static String searchPriceBooks() {
        
    }

    @AuraEnabled
    public static String getEntriesFromPriceBook() {
        
    }

    @AuraEnabled
    public static String createPriceBook() {
        
    }

    @AuraEnabled
    public static String updatePriceBook() {
        
    }

    @AuraEnabled
    public static String createEntry() {
        
    }

    @AuraEnabled
    public static String updateEntry() {
        
    }
}